### ISSUE TITLE
Todo list for 2015 workshop

### ISSUE THREAD

**Issue by jonnolen** [coderdojoindy/GirlsIncWorkshop#11]
- [ ] Print out physical activity sheets for mentors.
- [ ] Fix up game walkthrough with color blocks.
- [ ] Print out game walkthrough sheets, 1 for each student.
